"""Data-integrity checks for the intervals.icu calendar.

Two mechanisms have inflated training load in practice, and both are invisible
unless you go looking:

1. The same session recorded twice - e.g. Zwift plus an Apple Watch copy of the
   same ride. Both carry load, so the day counts double.
2. A planned workout "marked as done", which materialises the plan as a MANUAL
   activity alongside the real recording. Again both carry load.

This module finds those, plus activities that are unreadable via the API and
planned workouts that never got linked to what was actually done.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from typing import Any

from .intervals import IntervalsClient

# Two activities are the same session if their time ranges overlap by more than
# this fraction of the shorter one.
OVERLAP_THRESHOLD = 0.5

BIKE = {"Ride", "VirtualRide", "GravelRide", "MountainBikeRide"}
RUN = {"Run", "VirtualRun", "TrailRun"}


@dataclass
class Finding:
    kind: str
    date: str
    summary: str
    detail: list[str] = field(default_factory=list)
    load_at_risk: int = 0


def _span(activity: dict[str, Any]) -> tuple[dt.datetime, dt.datetime] | None:
    raw = activity.get("start_date_local")
    if not raw:
        return None
    start = dt.datetime.fromisoformat(raw)
    seconds = activity.get("elapsed_time") or activity.get("moving_time") or 0
    return start, start + dt.timedelta(seconds=seconds)


def _label(activity: dict[str, Any]) -> str:
    load = activity.get("icu_training_load")
    return (
        f"{activity.get('id'):>12}  {str(activity.get('source') or '-'):<13}"
        f"{str(activity.get('type') or '-'):<13} "
        f"{(activity.get('distance') or 0) / 1000:6.1f} km  "
        f"load {str(load if load is not None else '-'):>4}  "
        f"{(activity.get('name') or '')[:32]}"
    )


def find_duplicates(activities: list[dict[str, Any]]) -> list[Finding]:
    """Activities that overlap in time - the same session recorded twice."""
    by_day: dict[str, list[dict]] = {}
    for a in activities:
        if a.get("_note"):
            continue
        by_day.setdefault(a["start_date_local"][:10], []).append(a)

    findings = []
    for date, items in sorted(by_day.items()):
        if len(items) < 2:
            continue
        for i, first in enumerate(items):
            for second in items[i + 1 :]:
                sa, sb = _span(first), _span(second)
                if not sa or not sb:
                    continue
                overlap = (min(sa[1], sb[1]) - max(sa[0], sb[0])).total_seconds()
                shorter = min(
                    (sa[1] - sa[0]).total_seconds(), (sb[1] - sb[0]).total_seconds()
                )
                if shorter <= 0 or overlap / shorter < OVERLAP_THRESHOLD:
                    continue

                loads = [x.get("icu_training_load") or 0 for x in (first, second)]
                doubled = all(loads)
                findings.append(
                    Finding(
                        kind="duplicate",
                        date=date,
                        summary=(
                            f"two overlapping activities"
                            + (f" - both carry load ({loads[0]}+{loads[1]})" if doubled else "")
                        ),
                        detail=[_label(first), _label(second)],
                        load_at_risk=min(loads) if doubled else 0,
                    )
                )
    return findings


def find_plan_placeholders(activities: list[dict[str, Any]]) -> list[Finding]:
    """MANUAL activities generated by marking a planned workout as done.

    Signature: source MANUAL, linked to a planned event, and no recorded distance.
    """
    findings = []
    for a in activities:
        if a.get("_note") or a.get("source") != "MANUAL":
            continue
        if not a.get("paired_event_id") or (a.get("distance") or 0) > 0:
            continue
        findings.append(
            Finding(
                kind="placeholder",
                date=a["start_date_local"][:10],
                summary="planned workout materialised as a MANUAL activity (marked done)",
                detail=[_label(a)],
                load_at_risk=a.get("icu_training_load") or 0,
            )
        )
    return findings


def find_blocked(activities: list[dict[str, Any]]) -> list[Finding]:
    """Strava-synced activities that the API cannot read."""
    blocked = [a for a in activities if a.get("_note")]
    if not blocked:
        return []
    dates = sorted({a["start_date_local"][:10] for a in blocked})
    return [
        Finding(
            kind="blocked",
            date=dates[0],
            summary=f"{len(blocked)} activities unreadable via the API (synced from Strava)",
            detail=[", ".join(dates)],
        )
    ]


def find_unpaired(
    activities: list[dict[str, Any]], events: list[dict[str, Any]], today: dt.date
) -> list[Finding]:
    """Past planned workouts with a matching activity that day but no link."""
    by_day: dict[str, list[dict]] = {}
    for a in activities:
        if not a.get("_note"):
            by_day.setdefault(a["start_date_local"][:10], []).append(a)

    findings = []
    for e in events:
        if e.get("category") != "WORKOUT" or e.get("paired_activity_id"):
            continue
        date = e["start_date_local"][:10]
        if dt.date.fromisoformat(date) >= today:
            continue

        planned = e.get("type")
        group = BIKE if planned in BIKE else (RUN if planned in RUN else {planned})
        matches = [a for a in by_day.get(date, []) if a.get("type") in group]
        if not matches:
            continue
        findings.append(
            Finding(
                kind="unpaired",
                date=date,
                summary=f"planned {e.get('name')!r} never linked to what was done",
                detail=[f"  candidate: {_label(m)}" for m in matches],
            )
        )
    return findings


def run(client: IntervalsClient, days: int, today: dt.date | None = None) -> list[Finding]:
    today = today or dt.date.today()
    oldest = today - dt.timedelta(days=days)

    activities = client.activities(oldest=oldest, newest=today)
    events = client.events(oldest=oldest, newest=today)

    findings = (
        find_duplicates(activities)
        + find_plan_placeholders(activities)
        + find_unpaired(activities, events, today)
        + find_blocked(activities)
    )
    return sorted(findings, key=lambda f: (f.kind, f.date))
